config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end

  put '/post/:id/like', to: 'posts#like', as: 'like'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user

end

app/models/like_post.rb
class LikePost < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :user_id, uniqueness: {scope: :post_id}
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	has_many :like_posts, dependent: :destroy
	validates :article, :description, presence: true

	belongs_to :user

	def liked?(user)
		!!self.like_posts.find{|like| like.user_id == user.id}
		
	end

	paginates_per 10
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :like_posts
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	
	def new
		
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new
		@user = current_user
	end

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new(comment_params)
		if @comment.save
			redirect_to post_path(@post)
		else
			render :new
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:comment_description, :user_id)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: %i[show edit update destroy like]
	  before_action :authenticate_user!, except: [:index, :show]
	def index
		@post = Post.all.order("created_at DESC").page params[:page]
	end

	def new
		@post = Post.new
		@user = current_user
	end

	def show
		
		@comment = Comment.where(post_id: @post).order(created_at: :DESC)
		@user = User.find(@post.user_id)
		@total_like = LikePost.where(post_id: @post.id).count
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to post_path(@post)
		else
			render :new
		end

	end

	def edit

	end

	def update
		if @post.update(post_params)
			redirect_to post_path(@post)
		else
			render :edit
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end


	def like

		LikePost.create(user_id: current_user.id, post_id: @post.id)
		@users = User.all
		# @users.each do|user|
			UserMailer.example(User.new(email: current_user.email)).deliver
		# end
		redirect_to post_path(@post)
	end

	private

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:article, :description, :user_id)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/new.html.erb
<div style="margin-top:30px">
  <div class="col-md-6 offset-md-3">
  	<%= form_for([@post, @post.comments.build]) do |form| %>
    
    <div>
      <h2>Post a comment for <%=@post.article %></h2>
    </div>
    <div>
      <div class="form-group">
        <%= form.label :comment_description %><br>
        <%= form.text_area :comment_description , class: "form-control"%>
      </div>
        <%= form.hidden_field :user_id, value: current_user.id%>
      
      <div class="actions">
        <%= form.submit  %>
      </div>
    </div>  
  <% end %>
  </div>
</div>  

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">Post</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, Class: "nav-link"%> 
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Posts</a>
        </li>

        <li>
          <p class="navbar-text float-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </li>

      </ul>
      
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render 'layouts/header'%>

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="col align-self-center">
	<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :article %>
    <%= form.text_field :article, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
    <%= form.hidden_field :user_id , value: current_user.id %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<div>
	<%= render 'form', post: @post%>
	<%= link_to 'back', posts_path%>
</div>

app/views/posts/index.html.erb
<div style="margin-top:30px">
	<div>
		<button type="button" class="btn btn-primary"><%= link_to 'create new Post', new_post_path, class: "text-white" %></button>
	</div>
	<div class="row">	
		<% @post.each do |post|%>
			<div class="col-sm-3">
				<div class="card" style="margin: 10px;">
				  <div class="card-body">
				    <h5 class="card-title"><%= post.article %></h5>
				    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
				    <p class="card-text"><%= post.description %></p>
				    <%= link_to 'Show', post %>
					    
				    <% if user_signed_in? && post.user_id == current_user.id%>
					    <%= link_to 'Edit', edit_post_path(post)%>
					    <%= link_to 'Delete', post, method: :delete, data: {confirm: 'Aru you sure?'}%>
					<% end %>
				  </div>
				</div>
			</div>	
		<% end %>
	</div>	
	<div>
		<%= paginate @post  %>
	</div>
</div>

app/views/posts/new.html.erb
<div style="margin-top:30px">
	<div class="row">
		<div class= "col-md-6 offset-md-3">
			<%= render 'form', post: @post%>
			
			<%= link_to 'back', posts_path, class:"btn btn-info"%>
		</div>
		
	</div>
	
</div>

app/views/posts/show.html.erb
<div class="row">
	<div class="col-md-6 offset-md-3">
		<div>
			<h1 class="text-center"><%= @post.article%></h1>
		</div>
		<div>
			<p><%= @post.description%></p>

			<p><%= @user.email %></p>
		</div>
		<div>
			<% if user_signed_in? && current_user.id == @post.user_id %>
				<%= link_to 'Edit', edit_post_path(@post) %> 
			<% end %>
		</div>
		<div>
			<%= link_to 'back', posts_path %>
		</div>
		
	<!-- comment section -->
		<div class="row">
			<div class="col">
			<span class="text-primary"><b><%= @comment.count %></b></span>

			<%= link_to 'comment', new_post_comment_path(@post)%> 

			</div>

			<div class="col">
				<span><%= @total_like %> Likes</span>
				<% if user_signed_in? %>
					<% if @post.liked?(current_user) %>
						<%= button_to "like", like_path(@post), method: "put", disabled: true %>
					<% else %>
						<%= button_to "like", like_path(@post), method: "put" %>
					<% end %>
				<% end %>

			</div>
		</div>

		<% @comment.each do |comment| %>
			<div class="alert alert-dark" >
				
					<p><%= comment.comment_description %>
				
				<div>
					Likes
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="col-md-6">
	<h1>Welcome#index</h1>
	<p class="text-primary">Find me in app/views/welcome/index.html.erb</p>

</div>